version: '3'
services:
  node:
    build: .
    user: node
    working_dir: /home/node/app
    container_name: sst-api
    environment:
      - NODE_ENV=production
    volumes:
      - ./assets:/home/node/app/assets
      - ./db:/home/node/app/db
    expose:
      - "4000"
    ports:
      - "4000:4000"
    command: node build/index.js